repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/backplane/pre-commit-rust-hooks
    rev: v1.1.0
    hooks:
      - id: fmt
      - id: check
      - id: clippy
      - id: test
