//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "my_chat_member_update"
)]
pub enum MyChatMemberUpdate {
    #[sea_orm(string_value = "joined")]
    Joined,
    #[sea_orm(string_value = "left")]
    Left,
}
